### ISSUE TITLE
Build failed with Weston v8.0

### ISSUE THREAD

**Issue by s1ng0c** [sony/flutter-embedded-linux#102]
Trying to build `flutter-desktop-shell` but got error. The header file `config-parser.h` had been move to `libweston/config-parser.h` which is the main issue.

Please have a look.

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your report. We are aware of this issue and will fix it. Thank you!

See: https://github.com/sony/flutter-embedded-linux/issues/4#issuecomment-828121126

**Comment by HidenoriMatsubayashi** [comment]
Thank you so much. I fixed this issue.
