### ISSUE TITLE
Create flutter plugins for embedded Linux use

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#124]
We need to create flutter plugins for embedded Linux use. We would prepare another repo for it.

- [ ] Audio Player
- [ ] Connectivity
- [ ] Path provider
- [ ] Shared preference
- [ ] URL launcher
- [x] [Video Player](https://github.com/sony/flutter-embedded-linux/issues/174)
- [ ] WebView
- [ ] Camera
- [ ] WebRTC
etc.

**Comment by georgfaust** [comment]
how about supporting https://github.com/flutter-webrtc/flutter-webrtc?
The readme says Linux is WIP.

**Comment by HidenoriMatsubayashi** [comment]
I think it's not hard to add webrtc support (plugin) if we use GStreamer.

**Comment by HidenoriMatsubayashi** [comment]
I will close this because issues related to plugins will be managed [here](https://github.com/sony/flutter-elinux-plugins).
