### ISSUE TITLE
Flutter engine support for 32 bit ARM

### ISSUE THREAD

**Issue by kushflutter** [sony/flutter-embedded-linux#166]
@HidenoriMatsubayashi Do we have support available for ARM 32 bit?
Do we have plans to support it?
If i need to do by myself, any leads that can help?

**Comment by HidenoriMatsubayashi** [comment]
Technically, yes. This software (flutter-embedded-linux) doesn't have any CPU architecture-dependent implementations. However, there are some issues to ARM 32bit (armhf, ARMv7) support of the Flutter Engine.

- https://github.com/flutter/flutter/issues/83765
- https://github.com/flutter/flutter/issues/84133
- https://github.com/flutter/flutter/issues/74322
- https://github.com/flutter/flutter/issues/75823

**Comment by chinmaygarde** [comment]
Is this armv7s or armv6?

**Comment by kushflutter** [comment]
> Is this armv7s or armv6?

@chinmaygarde - This is for armv7

**Comment by HidenoriMatsubayashi** [comment]
Closing as known issues have been fixed.
