### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by dongzhangsun** [sony/flutter-embedded-linux#179]
hi,
This error occurs when I cross compile the flutter app（host:linux x64, target:linux arm64）。

${FLUTTER_SDK}/bin/cache/artifacts/engine/linux-arm64-release/clang_x64/gen_snapshot \
  --deterministic \
  --snapshot_kind=app-aot-elf \
  --elf=.dart_tool/flutter_build/flutter-embedded-linux/libapp.so \
  --strip \
  .dart_tool/flutter_build/flutter-embedded-linux/app.dill

Can't load Kernel binary: Invalid kernel binary format version.

**Comment by HidenoriMatsubayashi** [comment]
Could you confirm that the version between the Flutter SDK version and Flutter engine which you built are matched?
 See also: https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-apps#1-installing-flutter-sdk

**Comment by dongzhangsun** [comment]
> Could you confirm that the version between the Flutter SDK version and Flutter engine which you built are matched?
> See also: https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-apps#1-installing-flutter-sdk

Thank you. Everything is working right now！

**Comment by HidenoriMatsubayashi** [comment]
Great. I'll close this issues.
