### ISSUE TITLE
flutter display is very blurry.

### ISSUE THREAD

**Issue by dongzhangsun** [sony/flutter-embedded-linux#181]
My monitor is HDMI interface, resolution is 1920 × 1080, Now the display looks blurry（linux arm64）, but it is clear on my working computer(linux x64).

**Comment by dongzhangsun** [comment]
![IMG20210622102527](https://user-images.githubusercontent.com/60767897/122853449-d5045580-d344-11eb-9c95-c03c9ec5ad95.jpg)

**Comment by HidenoriMatsubayashi** [comment]
Actually, this has been on my mind for some time. The same symptomatism seems to occur with flutter desktop for linux. However, the texts are clear with flutter desktop for mac.

**Comment by HidenoriMatsubayashi** [comment]
I'll close this issue.

The flutter text’s default font size is 14 and I think it's small.
See https://madewithflutter.net/what-is-flutter-texts-default-font-size/

After changing the font size, it the text will be clear.
