### ISSUE TITLE
Add xdg-decoration protocol

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#216]
I don't know that Wayland compositors support xdg-decoration protocol and server-side decoration, but it's better to add xdg-decoration support?

### Protocol spec
https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml

### Related information
- GNOME: https://gitlab.gnome.org/GNOME/mutter/-/issues/217
- [Wayland-Protocols 1.15 Adds XDG-Decoration Protocol For Server-Side Window Decorations](https://www.phoronix.com/scan.php?page=news_item&px=Wayland-Protocols-1.15)

### Note
Wayland-protocol requires version 1.15 or higher.

**Comment by varbhat** [comment]
Hey @HidenoriMatsubayashi , Any updates on this?
I wanted to contribute regarding this.

**Comment by HidenoriMatsubayashi** [comment]
Thanks for your comments, but no updates.
