### ISSUE TITLE
Don't block raster thread until v-blank

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#220]
Obviously slow frames are more easily occurring with Wayland backend compared to X11 backend. Bottleneck is `eglSwapBuffers` and it takes about 18msec every frame.

### Wayland
![image](https://user-images.githubusercontent.com/62131389/132619808-c6a4a296-5844-4b80-a311-98f600cab6ca.png)

### X11
![image](https://user-images.githubusercontent.com/62131389/132619855-c4a40c39-5212-42bd-b1d0-5845e7815b57.png)

**Comment by HidenoriMatsubayashi** [comment]
Reopened because of https://github.com/sony/flutter-embedded-linux/pull/235

**Comment by Nagendra-Bankupalli** [comment]
@HidenoriMatsubayashi , I am testing flutter-elinux on ARM64 (imx8) platform, on wayland (drm-backend) , found the gpu and cpu utilisations are high for flutter-applications, would like to know  how to do better gpu profiling for flutter-elinux ? if this thread is not for gpu, please suggest me the right link,

**Comment by HidenoriMatsubayashi** [comment]
> would like to know how to do better gpu profiling for flutter-elinux ?

I think BSP vendors usually provide the GPU profiling tools. I recommend you use it to analyze GPU performance. Whereas, if you want to analyze flutter apps performance or this embedder, you can use [DevTools](https://docs.flutter.dev/testing/debugging).

**Comment by Nagendra-Bankupalli** [comment]
@HidenoriMatsubayashi , thank you for the inputs, sure will try devTools as well, but do we need to take any special care to enable GPU support while building flutter ?

**Comment by HidenoriMatsubayashi** [comment]
Yes, but can you check whether GPU is enabled in your target platform using some tools like glmark2?

**Comment by Nagendra-Bankupalli** [comment]
glmark2-es-wayland works fine on my HW!

**Comment by B-Nagendra** [comment]
Hi on my platform glmark2-es-wayland works well, but flutter gallery app is slow, what could be the issue?

**Comment by HidenoriMatsubayashi** [comment]
What device or board are you using?

**Comment by B-Nagendra** [comment]
its ARM64 based system

**Comment by HidenoriMatsubayashi** [comment]
Specifically?

**Comment by B-Nagendra** [comment]
its custom hw, its TI based  (PowerVR + openGLES 3.1), powrVR supprted in flutter 2.5.0 onwards , (not sure about flutter-elinux)
flutter-elinux version is 
Flutter 3.3.3 • channel unknown • unknown source
Framework • revision 18a827f393 (2 weeks ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

**Comment by B-Nagendra** [comment]
release version is better,still not good , glmark score is 114

**Comment by HidenoriMatsubayashi** [comment]
> glmark score is 114

It's too low... Is GPU HW accelerator enabled?

**Comment by B-Nagendra** [comment]
yes, will check why the score is low, thank you

**Comment by HidenoriMatsubayashi** [comment]
For some reason, this issue seems to be improved, but I can see it on both Wayland and X11 now.
