### ISSUE TITLE
[wayland] window decoration sometime doesn't appear in Weston 8

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#226]
The window decoration sometimes doesn't appear in Weston 8 even if we use the `-d` option to show the decorations, but there are no problems with other Wayland compositors. I'm not sure the cause, but https://github.com/sony/flutter-embedded-linux/pull/221 change is affecting it.

### Related issues
- https://github.com/sony/flutter-embedded-linux/issues/6

**Comment by psstoyanov** [comment]
Weird, with Weston 9 sometimes the decorations aren't displayed until it detects a mouse movement (haven't tried on touch enabled device with Weston for now). 
Once the movement is detected, the decoration buttons show up.
There is slight variance between the decoration strip showing and not but in both cases they appear once there is mouse movement.

Is this the same observation?
https://user-images.githubusercontent.com/3979134/149368076-0cf6f193-0944-46ee-99e3-a8da9a17d2d8.mp4

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your comment. Yes, it is.

**Comment by HidenoriMatsubayashi** [comment]
Closing as it seems to work fine on top of master branch.
