### ISSUE TITLE
input event regression elinux 2.5.0 -> (2.5.1 & 2.5.2 & 2.5.3)

### ISSUE THREAD

**Issue by ojdkGFS** [sony/flutter-embedded-linux#234]
HW: IMX8 mini quad  (variscite hw with debian bullseye image)

steps to reproduce:
generate simplest flutter app ->  flutter-elinux create testapp   
test:
  -  application works on elinux 2.5.0 
  - on elinux 2.5.1, 2.5.2, and 2.5.3 the application builds.  When running the application runs it  does not react to touch-input or mouse input. On rare occasions it will accept a few (1-5) input events just after launch, but will then no longer respond.

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your report. This is a known issue and is due to https://github.com/sony/flutter-embedded-linux/issues/230. Thanks a lot.
