### ISSUE TITLE
[wayland]GIF image display, increasing memory, unable to free memory.

### ISSUE THREAD

**Issue by dazuo0312** [sony/flutter-embedded-linux#245]
Flutter -elinux runtime environment: ARM64, Debian, NXP iMX8  
The interface runs to display GIF images, and the memory continues to increase, starting at 286M, 12 hours later, up to 900M.
flutter-elinux build elinux --release -d elinux-wayland
Here is sample code for the test.
[hmi_ani](https://github.com/dazuo0312/hmi_ani)

**Comment by nbhhcty** [comment]
I have the same problem

**Comment by suyulin** [comment]
> free
It's not a wayland framework problem, flutter's 🐞。You can use frame animation to solve this problem。

**Comment by dazuo0312** [comment]
> > free
> > It's not a wayland framework problem, flutter's 🐞。You can use frame animation to solve this problem。
Can you provide a demo?
I use frame animation, but the problem still exists.
Animationcontroller is used.
Webp animation also has this problem.
Running in X11 mode, there is no problem, only in Wayland mode.

**Comment by suyulin** [comment]
Webp animation on Android , the memory is ok ?

**Comment by dazuo0312** [comment]
> Webp animation on Android , the memory is ok ?

yes

**Comment by suyulin** [comment]
> > Webp animation on Android , the memory is ok ?
> 
> yes

Flutter version is 2.5.2 ?

**Comment by dazuo0312** [comment]
> > > Webp animation on Android , the memory is ok ?
> > 
> > 
> > yes
> 
> Flutter version is 2.5.2 ?

Flutter version is :2.5.0  or 2.8.1.

**Comment by renehansen** [comment]
We have the same problem, and in addition to the approaches already mentioned, we can confirm that Lottie and Flare cause memory leaks as well, which means that there is basically no way of doing animations at the moment.  

Flutter version: 2.10.3

**Comment by dazuo0312** [comment]
@HidenoriMatsubayashi  I used ARM64, Debian, NXP iMX8.
There is this problem on the arm64 board.

**Comment by renehansen** [comment]
Yes, I am also experiencing the leak on arm64. Btw, here is the [source code](https://github.com/renehansen/leak_poc) that contains a frame animation, as well as Lottie, and Flare animations

**Comment by HidenoriMatsubayashi** [comment]
Can anyone use debugging tools like `Valgrind` to investigate the memory leak points?

**Comment by oz2mia** [comment]
Using valgrind does not work, the program will not start correct.
I have tried using google/sanitizers that are build in the flutter engine, used LSAN and ASAN, but they only report heap used,
but not where the leak is.

**Comment by HidenoriMatsubayashi** [comment]
I see. Thanks. Would it be possible for you to send the PR?

**Comment by HidenoriMatsubayashi** [comment]
Closing.
