### ISSUE TITLE
Support for raw opengl textures

### ISSUE THREAD

**Issue by HrX03** [sony/flutter-embedded-linux#247]
I am currently developing a wayland compositor which needs to send the window opengl textures to flutter. I tried getting the pixels from the texture and then using them for a PixelBufferTexture but there's some middle step that is failing and i think having a direct opengl texture would benefit my project (plus better performance, i don't need to get pixels and then send those, just send the direct texture). As there is already a base FlutterOpenGLTexture i don't think it would be too complicate to introduce and would benefit many people other than me

**Comment by HidenoriMatsubayashi** [comment]
Thank you for creating the issue. However, it seems duplicated of https://github.com/sony/flutter-embedded-linux/issues/157. But, thanks a lot. Please watch #157
