### ISSUE TITLE
Is gpu necessary？

### ISSUE THREAD

**Issue by camel007** [sony/flutter-embedded-linux#249]
my device has a a53 cpu, but banned mali gpu

**Comment by HidenoriMatsubayashi** [comment]
Yes! Soft-rendering will be too slow.

**Comment by HDB8129** [comment]
Hi @HidenoriMatsubayashi ,

Assuming there will be slow and rendering , high CPU load , low FPS without GPU.

But is there any way or solution to achieve the above parameters fine without GPU ?
