### ISSUE TITLE
How to use it on Jetson Nano?

### ISSUE THREAD

**Issue by fayfive** [sony/flutter-embedded-linux#264]
I have followed the steps
```
$ flutter-elinux create sample
$ cd sample
$ flutter-elinux run -d elinux-wayland
```
But it just run on ubuntu x86
I want to run it on DRM mode of Jetson Nano. How to use it?
Can I cross compile the flutter app?
Thanks!

**Comment by HidenoriMatsubayashi** [comment]
Closing this issue as duplication of https://github.com/sony/flutter-elinux/issues/98
