### ISSUE TITLE
Add support for building for arm64

### ISSUE THREAD

**Issue by apy7hst** [sony/flutter-embedded-linux#272]
Please add support for building flutter for embedded linux for arm64 as well. This repository supports building only for amd64.

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure, but developers can cross-build...

**Comment by apy7hst** [comment]
> I'm not sure, but developers can cross-build...

Even I am trying to develop this for ubuntu touch and it is arm64. But it fails when I build it using the arm64 libffi7 package, and it says the problem is it is amd64.

**Comment by apy7hst** [comment]
> I guess it's a problem on your environment (os). Because I can build this software on arm64 devices such as Raspberry Pi4. Also, this software doesn't have any implementation of CPU arch dependencies.

The host os I am building this on is ubuntu touch
