### ISSUE TITLE
STM32MP1 with FLUTTER

### ISSUE THREAD

**Issue by gencay3535** [sony/flutter-embedded-linux#284]
I am trying to build my image with flutter, I actually followed this [workflow with dunfell branch](https://github.com/meta-flutter/meta-flutter/blob/dunfell/.github/workflows/dunfell-stm32mp15.yml) but I am working with kirkstone. I keep getting an error about flutter-engine so I could not be able to build an image. I am very new to these topics so can you lead me how can I proceed for my work?

Here is what I've done so far. 
I've created an image with wayland support then I added layers for meta-flutter and clang and did the configurations like in the workflow with the kirkstone syntax. but my flutter-engine do_install task keeps crashing. Here is the task:
`do_install() {

    install -D -m0644 ${S}/${OUT_DIR_REL}/so.unstripped/libflutter_engine.so \
        ${D}${libdir}/libflutter_engine.so
    
    if ${@bb.utils.contains('PACKAGECONFIG', 'desktop-embeddings', 'true', 'false', d)}; then
        install -m0644 ${S}/${OUT_DIR_REL}/so.unstripped/libflutter_linux_gtk.so ${D}${libdir}
    fi

    install -D -m0644 ${S}/${OUT_DIR_REL}/flutter_embedder.h \
        ${D}${includedir}/flutter_embedder.h

    install -D -m0644 ${S}/${OUT_DIR_REL}/icudtl.dat \
        ${D}${datadir}/flutter/icudtl.dat

    # create SDK
    install -D -m0755 ${S}/${OUT_DIR_REL}/clang_x64/gen_snapshot \
        ${D}${datadir}/flutter/sdk/clang_x64/gen_snapshot
    
    cd ${S}/flutter
    echo `git rev-parse HEAD` > ${D}${datadir}/flutter/sdk/engine.version
    echo ${FLUTTER_ENGINE_REPO_URL} >> ${D}${datadir}/flutter/sdk/engine.version
    echo ${@get_flutter_sdk_version(d)} >> ${D}${datadir}/flutter/sdk/flutter_sdk.version

    cd ${D}/${datadir}/flutter
    zip -r engine_sdk.zip sdk
    rm -rf sdk
}
do_install[depends] += "zip-native:do_populate_sysroot"
`
Do you have any idea where I am wrong or what path do I need to follow to run my custom flutter applications on my stm32mp1 board?

**Comment by HidenoriMatsubayashi** [comment]
> I am trying to build my image with flutter, I actually followed this [workflow with dunfell branch](https://github.com/meta-flutter/meta-flutter/blob/dunfell/.github/workflows/dunfell-stm32mp15.yml)

Please create an issue on https://github.com/meta-flutter/meta-flutter.
