### ISSUE TITLE
Building flutter-engine with fontconfig support

### ISSUE THREAD

**Issue by andreadaoud** [sony/flutter-embedded-linux#289]
If we want to display CJK characters using system font, we have to enable fontconfig support. Just add `--enable-fontconfig` to `./flutter/tools/gn` command. Could you please consider enabling this in your CI pipeline when you build the artifacts?

**Comment by HidenoriMatsubayashi** [comment]
Hi @taka-okayama 

This request is understandable/reasonable to me. 

> Just add --enable-fontconfig to ./flutter/tools/gn command. Could you please consider enabling this in your CI pipeline when you build the artifacts?

Can you please address that? All you have to do is add `--enable-fontconfig` to the build script in the CI.

Updated to add --enable-fontconfig: 
https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-Engine-from-source#4-build-embedder

**Comment by HidenoriMatsubayashi** [comment]
@taka-okayama ping

**Comment by taka-okayama** [comment]
@HidenoriMatsubayashi
sorry, we have a problem in CI now.

**Comment by HidenoriMatsubayashi** [comment]
@taka-okayama Ok, then please change the recipe after the CI is green.

**Comment by taka-okayama** [comment]
https://github.com/flutter/flutter/issues/112919

**Comment by HidenoriMatsubayashi** [comment]
Thanks. Commented.

**Comment by taka-okayama** [comment]
@andreadaoud @HidenoriMatsubayashi 

I've updated artifacts with `--enable-fontconfig`. Could you confirm?

**Comment by HidenoriMatsubayashi** [comment]
@taka-okayama 

You mean you updated https://github.com/sony/flutter-embedded-linux/releases/tag/c08d7d5efc and its build includes that option? Or you just changed only internal recipe change?

**Comment by taka-okayama** [comment]
@HidenoriMatsubayashi 

oh, sorry. Local CI completed but deployment step in CI was skipped because of no change in flutter version. I'm changing CI script to re-build artifacts forcibly(option).

**Comment by HidenoriMatsubayashi** [comment]
Understood, but it's OK for me to wait until next release.

**Comment by andreadaoud** [comment]
I've already compiled myself, so waiting until next release is also okay for me. But I'm willing to test anytime.

**Comment by taka-okayama** [comment]
@HidenoriMatsubayashi @andreadaoud 

thanks for your patience. this change will be deployed next release.

**Comment by HidenoriMatsubayashi** [comment]
@taka-okayama Confirmed that this option was included in the artifacts for v3.3.5. Thanks. I'll close the issue.
