### ISSUE TITLE
Is this understanding correct？

### ISSUE THREAD

**Issue by SinkinZhu** [sony/flutter-embedded-linux#294]
Dear Sir

Flutter Plugins that support Linux platforms from https://pub.dev/ can run normally on flutter-elinux. 
Is this understanding correct？
Thanks！

**Comment by HidenoriMatsubayashi** [comment]
Basically, I would say No. But it depends on a plugin. Plugin interfaces and platform specific implementations are different for each platform. Plugins implemented only by Dart code can be used for all platforms.
