### ISSUE TITLE
Install flutter on Variscite i.MX8M Nano

### ISSUE THREAD

**Issue by marco-1988** [sony/flutter-embedded-linux#298]
Hello everybody

I would need help installing flutter in a Variscite card equipped with i.MX8M Nano processor.

I started to follow the guide, but it is not clear to me how to proceed and in what order the various steps should be followed.

Then is there a way to compile on a macOS with M1 and then run on this card?

The things that are mostly unclear to me are where it says to refer to the cmake build path, and also where to find the flutter-client it refers to in some places in the guide, but I don't find where this is installed.

Thank you

**Comment by HidenoriMatsubayashi** [comment]
Sorry for no response.

> Then is there a way to compile on a macOS with M1 and then run on this card?

No, it cannot. You need to use Linux OS.

> The things that are mostly unclear to me are where it says to refer to the cmake build path, and also where to find the flutter-client it refers to in some places in the guide, but I don't find where this is installed.

After build passed, you can find it in your build directory (e.g. build/).
