### ISSUE TITLE
Tap events are not notified correctly.

### ISSUE THREAD

**Issue by makotosato-at** [sony/flutter-embedded-linux#300]
Hello.

I have encountered problems using a multi-tap display and i.MX8MP board.
In flutter_elinux_view.h/.cc, instance variable _touch_event__ is not initialized, so it contains an garbage value.
Therefore, it is not processed correctly in function _GgeTouchPoint()_.

I think it needs to be initialized as follows:
```
struct touch_event {
    touch_point points[10] = {
      {false, -1, 0, .0, .0}, {false, -1, 0, .0, .0},
      {false, -1, 0, .0, .0}, {false, -1, 0, .0, .0},
      {false, -1, 0, .0, .0}, {false, -1, 0, .0, .0},
      {false, -1, 0, .0, .0}, {false, -1, 0, .0, .0},
      {false, -1, 0, .0, .0}, {false, -1, 0, .0, .0},
    };
  };
```

**Comment by HidenoriMatsubayashi** [comment]
Thank you for reporting the bug.
