### ISSUE TITLE
Drm VS Wanyland

### ISSUE THREAD

**Issue by suyulin** [sony/flutter-embedded-linux#308]
hi,  I found that Wayland's performance is better than DRM's, with Wayland reaching 60FPS while DRM only reaches 30FPS. Why is this? 
<img width="607" alt="image" src="https://user-images.githubusercontent.com/6275411/209747357-34801268-0604-4022-b490-d35e993bc52a.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/6275411/209747390-c8ed4250-34f9-4332-b1d7-178c2609d081.png">

**Comment by HidenoriMatsubayashi** [comment]
Sorry, I'll close this ticket as I guess this issue depends on DRM driver or KMS display settings.
