### ISSUE TITLE
Screen corruption on Wayland (Not repainted?)

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#326]
The screen is distorted with high rate with flutter 3.7.0.

<img width="1278" alt="スクリーンショット 2023-01-25 23 58 50" src="https://user-images.githubusercontent.com/62131389/214598177-f6ee66a3-3def-47aa-b46a-924257d5b4f2.png">

**Comment by HidenoriMatsubayashi** [comment]
It seems this symptom depends on Ubuntu 22 (GNOME).

**Comment by swift-kim** [comment]
Is this issue possibly related to https://github.com/flutter/flutter/issues/119601? Does it only occur under some specific conditions (Ubuntu/Wayland)?

**Comment by HidenoriMatsubayashi** [comment]
Could be. Thanks for the information. Actually, I was not able to reproduce this issue on X11 backend and Sway (Wayland compositor). I can reproduce it only on Ubuntu 22 (GNOME, Weston).

**Comment by andreadaoud** [comment]
Can you patch this when building flutter engine in CI pipeline? From my testing, the following patch solves this issue:

```
diff --git a/shell/platform/embedder/embedder_surface_gl.cc b/shell/platform/embedder/embedder_surface_gl.cc
index 44b1fddf80..5b64ad2e28 100644
--- a/shell/platform/embedder/embedder_surface_gl.cc
+++ b/shell/platform/embedder/embedder_surface_gl.cc
@@ -88,8 +88,7 @@ SurfaceFrame::FramebufferInfo EmbedderSurfaceGL::GLContextFramebufferInfo()
   // Enable partial repaint by default on the embedders.
   auto info = SurfaceFrame::FramebufferInfo{};
   info.supports_readback = true;
-  info.supports_partial_repaint =
-      gl_dispatch_table_.gl_populate_existing_damage != nullptr;
+  info.supports_partial_repaint = false;
   return info;
 }
```

**Comment by HidenoriMatsubayashi** [comment]
I'm considering adding populate_existing_damage support instead.
