### ISSUE TITLE
Debug mode doesn't work on the DRM backend.

### ISSUE THREAD

**Issue by Mai-Matsuura** [sony/flutter-embedded-linux#33]
Flutter applications in debug mode don't work on the DRM backend.  
The application crashes with the following log:
```
[FATAL:flutter/fml/memory/weak_ptr.h(122)] Check failed: (checker_.checker).IsCreationThreadCurrent(). 
```

Related: https://github.com/sony/flutter-embedded-linux/issues/15#issuecomment-800447168

**Comment by Mai-Matsuura** [comment]
@psstoyanov
I fixed this issue. Flutter applications in debug mode work on the DRM backend using the latest flutter-embedded-linux.

**Comment by psstoyanov** [comment]
Just tried it on the PinebookPro/ PinePhone with DRM and it worked well on both!

Thank you, @Mai-Matsuura , I believe this ticket can be closed :+1:

**Comment by Mai-Matsuura** [comment]
I close this ticket. Thank you, @psstoyanov .
