### ISSUE TITLE
Internal CI for Engine artifacts doesn't work

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#395]
Hi @taka-okayama 

It looks like the internal CI for building and uploading Engine artifacts hasn't worked as version 3.13.8 and 3.13.9 are missing.
https://docs.flutter.dev/release/archive?tab=linux

Can you please check the CI and its scripts? Thanks.

**Comment by taka-okayama** [comment]
@HidenoriMatsubayashi thanks for your notification

I fixed this issue with internal CI and kicked it now. i would appreciate your patience.

Reason of CI failure:  
- [python3 version mismatch](https://chromium.googlesource.com/chromium/tools/depot_tools.git#depot_tools)

**Comment by HidenoriMatsubayashi** [comment]
Thanks for the fix! Closing.
