### ISSUE TITLE
Does this project run without systemd?

### ISSUE THREAD

**Issue by godalming123** [sony/flutter-embedded-linux#402]
Systemd is listed as a dependency for the libDRM backend. Is this required, or does it just add some additional functionality? If it just adds functionality, then what functionality?

**Comment by HidenoriMatsubayashi** [comment]
Yes, it's mandatory for event loop implements.

See:
- https://github.com/sony/flutter-embedded-linux/blob/6b14cf0887fef389a2df23336947245e6d2ce10a/src/flutter/shell/platform/linux_embedded/window/elinux_window_drm.h#L64
- https://manpages.debian.org/testing/libsystemd-dev/sd-event.3.en.html

Thanks.
