### ISSUE TITLE
Support Platform views

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#41]
We need to add support Platform views support to embed native views like WebView in a Flutter app

**Comment by jwinarske** [comment]
[Hybrid Composition](https://github.com/flutter/flutter/wiki/Hybrid-Composition).  Please read the Performance section.

The problem with the embedded space is that one size doesn't fit all.  So having a generic Platform view solution may not meet the general communities needs.  Please keep this in mind when looking at potential solutions.

**Comment by CodeDoctorDE** [comment]
What's the status of this issue?

**Comment by HidenoriMatsubayashi** [comment]
Sorry for no updates.

Platform views implementation (embedder side) has already been merged into this repo. On Dart side, I'll merge https://github.com/sony/flutter-elinux/pull/206 (this new package for platform views) when I release next flutter-elinux version (3.13.1).

Thanks. Closing.
