### ISSUE TITLE
Add sleep to wait for the next event in the main loop properly

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#43]
Currently, there isn't any sleep to wait for the next event in the main loop properly. Therefore, it is high CPU usage.

main.cc
```cpp
  // Main loop.
  while (flutter_controller->view()->DispatchEvent()) {
    flutter_controller->engine()->ProcessMessages();
  }
```

**Comment by LefixBlue** [comment]
@HidenoriMatsubayashi 

That's obviously the one I was talking about when I reported my test results on the raspberrypi-64 yocto build in #4

**Comment by HidenoriMatsubayashi** [comment]
Yes, I think so. Thank you for your report!

**Comment by HidenoriMatsubayashi** [comment]
I fixed this issue https://github.com/sony/flutter-embedded-linux/pull/45. Thank you so much!
