### ISSUE TITLE
Host Platform Target Plaform Documentation

### ISSUE THREAD

**Issue by Charlie9830** [sony/flutter-embedded-linux#56]
I've just finished successfully building for an RPi4 with the DRM Backend. Thanks for all your hard work guys.
I did have a small head scratching hiccup during the process though. I had to perform Step 3 ```Build for DRM Backend``` on the target device (RPi4). With a libflutter_engine.so targeting arm64, this step of the build would fail on my X64 machine. 
If this is expected behavior then I think it would be worth adding a note to Step 3 that the following steps must be built on the target platform (Similar to the note about compiling the Dart/Flutter code)

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your comments.

> With a libflutter_engine.so targeting arm64, this step of the build would fail on my X64 machine.

Did you try to cross-build for arm64 on x64 hosts, right?

I'll add add cross-build support and update README.

**Comment by Charlie9830** [comment]
Hi Hidenori,

I think where my confusion lies is around step 3. Does step 3 have to be performed on the target platform? I understand that the Flutter project build ```flutter build linux``` does not allow for cross-building (currently). Is this also the case for Step 3?

**Comment by HidenoriMatsubayashi** [comment]
Yes, you are right. THE current README is not good, so I'll update it.

**Comment by HidenoriMatsubayashi** [comment]
We've updated README. https://github.com/sony/flutter-embedded-linux/pull/101
