### ISSUE TITLE
Add cross-build support for arm64 on x64 hosts (CMake build script)

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-embedded-linux#57]
We need to modify CMake files and README  to add cross-build for arm64 targets on x64 hosts support. https://github.com/sony/flutter-embedded-linux/issues/56

**Comment by HidenoriMatsubayashi** [comment]
@TomohideMorimoto Will you handle this with https://github.com/sony/flutter-embedded-linux/issues/30?

**Comment by topolittle** [comment]
I just added a patch in issue #30 related to this

**Comment by TomohideMorimoto** [comment]
@HidenoriMatsubayashi   
Start working.
