### ISSUE TITLE
log message is incorrect

### ISSUE THREAD

**Issue by bamchoh** [sony/flutter-embedded-linux#83]
https://github.com/sony/flutter-embedded-linux/blob/e0e1e80b579641f5b66e18a1db1d3930a72c68db/src/flutter/shell/platform/linux_embedded/window/native_window_drm.h#L104

I think a suitable message is "Couldn't find a encoder"

**Comment by HidenoriMatsubayashi** [comment]
Thank you for your report. That's typo. I'll fix that.

**Comment by HidenoriMatsubayashi** [comment]
Thanks a lot.
