### ISSUE TITLE
weston >= 8

### ISSUE THREAD

**Issue by jwinarske** [sony/flutter-embedded-linux#94]
Embedders hang when using weston >= 8.  It should also reflect in test matrix version of compositor.

Tests should be based on Dunfell (LTS) or later.

**Comment by HidenoriMatsubayashi** [comment]
> Embedders hang when using weston >= 8

Could you inform me of more details? Does it always hang due to a specific operation?

**Comment by jwinarske** [comment]
It hangs before the engine starts.  Same behavior on weston-9.

**Comment by jwinarske** [comment]
It is definatly a bug

**Comment by HidenoriMatsubayashi** [comment]
I've fixed some bugs. There might still be bugs, but I can't get any information from this issue. I'll close this once. Thanks.
